# =============================================================
# output/code_writer.py
# Saves generated C code to files in the generated/ folder.
#
# Phase 8 feature — used when OUTPUT_MODE includes "code".
# Designed now so Phase 8 slots in without changes.
#
# Output structure:
#   generated/
#   ├── clock_config.c
#   ├── usart1_config.c
#   ├── spi2_config.c
#   └── mcu_config.h     ← combined header
# =============================================================

import os
import re
from datetime import datetime
from pathlib  import Path
from Config   import GENERATED_CODE_PATH


# =============================================================
# FOLDER SETUP
# =============================================================

def _ensure_generated_folder() -> None:
    """Create the generated/ folder if it does not exist."""
    Path(GENERATED_CODE_PATH).mkdir(exist_ok=True)


def _sanitize_name(name: str) -> str:
    """
    Convert a peripheral name to a safe filename.
    e.g. "USART1 @ 115200" → "usart1_115200"
    """
    name = name.lower()
    name = re.sub(r'[^a-z0-9_]', '_', name)
    name = re.sub(r'_+', '_', name)
    return name.strip('_')


# =============================================================
# CODE FILE WRITER
# =============================================================

def save_c_file(
    code: str,
    peripheral: str,
    controller: str,
    ide: str,
) -> str:
    """
    Save generated C code to a .c file.

    Parameters
    ----------
    code       : the generated C code string
    peripheral : e.g. "USART1", "SPI2", "clock"
    controller : e.g. "STM32F407VGT6"
    ide        : e.g. "STM32CubeIDE"

    Returns
    -------
    Path to the saved file.
    """
    _ensure_generated_folder()

    filename = f"{_sanitize_name(peripheral)}_config.c"
    filepath = os.path.join(GENERATED_CODE_PATH, filename)

    # Add file header if not already present
    if not code.strip().startswith("/*"):
        header = _build_file_header(peripheral, controller, ide)
        code = header + "\n" + code

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"  ✅ Saved: {filepath}")
    return filepath


def save_h_file(
    declarations: list[str],
    controller: str,
) -> str:
    """
    Save or update the combined header file.
    Adds function declarations for all generated init functions.

    Parameters
    ----------
    declarations : list of function declaration strings
                   e.g. ["void USART1_Init(void);"]
    controller   : e.g. "STM32F407VGT6"

    Returns
    -------
    Path to the saved header file.
    """
    _ensure_generated_folder()

    guard   = "MCU_CONFIG_H"
    filepath = os.path.join(GENERATED_CODE_PATH, "mcu_config.h")

    lines = [
        f"/* mcu_config.h — Generated by MCU Dev Assistant",
        f" * Controller : {controller}",
        f" * Generated  : {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f" */",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"",
        f"/* ── Generated Initialization Functions ──────────── */",
    ]
    for decl in declarations:
        lines.append(decl)
    lines += ["", f"#endif /* {guard} */", ""]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"  ✅ Saved header: {filepath}")
    return filepath


def _build_file_header(
    peripheral: str,
    controller: str,
    ide: str,
) -> str:
    """Build a standard C file header comment block."""
    return (
        f"/*\n"
        f" * {_sanitize_name(peripheral)}_config.c\n"
        f" * Generated by MCU Dev Assistant\n"
        f" *\n"
        f" * Controller : {controller}\n"
        f" * IDE        : {ide}\n"
        f" * Generated  : "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f" *\n"
        f" * IMPORTANT: All register values are sourced from\n"
        f" * the documents you uploaded. Verify against your\n"
        f" * specific hardware revision before flashing.\n"
        f" */\n\n"
    )


# =============================================================
# CODE EXTRACTION
# =============================================================

def extract_c_code(llm_response: str) -> str:
    """
    Extract C code blocks from an LLM response.

    The LLM may wrap code in markdown fences:
```c
    void USART1_Init(void) { ... }
```

    This function extracts just the code.

    Parameters
    ----------
    llm_response : raw LLM response string

    Returns
    -------
    Clean C code string, or full response if no fence found.
    """
    # Try to find ```c ... ``` block
    pattern = re.compile(
        r'```(?:c|C)?\s*\n(.*?)```',
        re.DOTALL
    )
    matches = pattern.findall(llm_response)

    if matches:
        # Join multiple code blocks if present
        return "\n\n".join(m.strip() for m in matches)

    # No markdown fence — check if response looks like C code
    if (
        "void " in llm_response or
        "int "  in llm_response or
        "#include" in llm_response or
        "RCC->" in llm_response
    ):
        return llm_response.strip()

    # Return as-is — let the caller decide
    return llm_response.strip()


def list_generated_files() -> list[str]:
    """
    List all files in the generated/ folder.

    Returns
    -------
    List of filenames e.g. ['clock_config.c', 'usart1_config.c']
    """
    _ensure_generated_folder()
    return [
        f for f in os.listdir(GENERATED_CODE_PATH)
        if f.endswith(('.c', '.h'))
    ]


def clear_generated_files() -> int:
    """
    Delete all generated C/H files.

    Returns
    -------
    Number of files deleted.
    """
    _ensure_generated_folder()
    count = 0
    for filename in list_generated_files():
        filepath = os.path.join(GENERATED_CODE_PATH, filename)
        os.remove(filepath)
        count += 1
    print(f"  Cleared {count} generated file(s).")
    return count